# Generated by Django 5.2.7 on 2025-10-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldtrade', '0003_goldprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldprice',
            old_name='price_per_gram',
            new_name='buy_price_per_gram',
        ),
        migrations.AddField(
            model_name='goldprice',
            name='sell_price_per_gram',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
