# Generated by Django 5.2.7 on 2025-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldtrade', '0004_rename_price_per_gram_goldprice_buy_price_per_gram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=2, help_text='Buy rate per gram in LKR', max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=2, help_text='Sell rate per gram in LKR', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
