# Generated by Django 5.2.7 on 2025-10-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldtrade', '0005_goldrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoldPrice',
        ),
    ]
